### ISSUE TITLE
Reduce binary sizes

### ISSUE THREAD

**Issue by floatdrop** [sindresorhus/win-clipboard#15]
Moving from C to Rust gives us ready to use library for clipboard management, but also gives us large binary sizes.

------

Articles to read:

https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html
https://jamesmunns.com/update/2018/04/01/tinyrocket.html

**Comment by Qix-** [comment]
This is part of the reason why I asked *why* in the PR 😅 C creates competitively small binaries. I don't think moving to a whole new language in order to solve line ending issues was necessarily the most practical move, personally.

I'm very skeptical of begin able to get binary sizes down in a Rust binary.

**Comment by sindresorhus** [comment]
I don’t see the current binary size as problem.
